doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            App\Admin:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Admin/Entity'
                prefix: 'App\Admin\Entity'
                alias: App\Admin
            App\Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Entity'
                prefix: 'App\Core\Entity'
                alias: App\Core
            App\Payment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Payment/Entity'
                prefix: 'App\Payment\Entity'
                alias: App\Payment
